### PR TITLE
PICC_Select, MFRC522.cpp

### PR DESCRIPTION
**Pull request by tuyethoa08041997**
This change should be test on real hardware first...
fix issue https://github.com/miguelbalboa/rfid/issues/238

### CODE REVIEW

**Comment by Rotzbua** [comment]
General note: travis actually broken, not a code issue.

**Comment by Rotzbua** [comment]
@tuyethoa08041997 Could you test this possible bugfix?

**Comment by tuyethoa08041997** [comment]
@Rotzbua Sorry, I don't have this module anymore.

**Comment by Rotzbua** [comment]
@tuyethoa08041997 Thanks for your reply. I had a look at this part of the code.

The part `currentLevelKnownBits = collisionPos; ` makes no sence anyway, because `currentLevelKnownBits` is no global or static. So the result is not used. Maybe this is hint at bugs, idk..

But your patch seems correct for me.

**Pull request merged**
