### PR TITLE
Add Espressif ESP8266 support in library manifest

### PR DESCRIPTION
**Pull request by danielcbit**
Add support for ESP8266 so that it could be installed from platformio lib management system.

### CODE REVIEW

**Comment by Rotzbua** [comment]
@danielcbit Does it work without lib changes?

**Comment by danielcbit** [comment]
Yes, I'm currently using it in a project. Thats Why I thought a bit strange not having this already.
I'm using platform IO to manage the project, and the lib does not get installed because the espressif platform is not declared.

**Comment by Rotzbua** [comment]
@danielcbit Ok. I'm not familiar with platform IO, so it uses https://github.com/esp8266/Arduino to compile the library?

**Comment by danielcbit** [comment]
Hi. @Robtzbua

Yes, it uses the Arduino framework. That's why it is needed only to add the espressif platform to the lib manifest.

You can build using other frameworks for ESP8266,  but for Arduino it works.

**Comment by Rotzbua** [comment]
@danielcbit  Thanks. New stuff learned :)

**Pull request merged**
