### PR TITLE
added ESP8266 support

### PR DESCRIPTION
**Pull request by beyondszine**
Hi,
please let me know if there is something that I am missing with this PR

### CODE REVIEW

**Comment by beyondszine** [comment]
@omersiar 
I checked it up in the ESP8266 arduino doc, this one is fixed and defined in sdk's spi_flash.h file. 
I checked with other users also, 
https://github.com/esp8266/Arduino/issues/2421

**Comment by beyondszine** [comment]
@omersiar while working and testing the codes, I have got some serious changes and trying to port a few of the examples as in this repository to esp8266.  So how to go about these ?
I mean just update the older examples and the wiring diagram with pcb schematic ?

**Comment by beyondszine** [comment]
Thanks @omersiar I will take care of your suggestion and will try to implement it if I can. 
Yeah, I understand now how my PR to master branch is not apt.  I am developing it in my seperate branch and maybe we can incorporate that after full development.
What say ?

**Comment by TheNitek** [comment]
Not sure you know this, but you can wrap the ESP specific code like this:
```
#if defined(ESP8266)
	yield();
#endif
```
to prevent any influence on the other platforms

**Comment by beyondszine** [comment]
@TheNitek 
I have indeed seen that in lines of code for ESP, but not yet sure about the yield function, cudn't get the chance to peek into it.
But thanks to you, I am surely going to keep this in mind for further codes.

**Pull request closed without merging**
