### PR TITLE
fix bug in issue #432

### PR DESCRIPTION
**Pull request by EndangeredF1sh**
try to fix problem in #432 issue

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Doc update?   | no
| BC breaks?    | no 
| Deprecations? | no
| Fixed tickets | #432

### CODE REVIEW

**Comment by Rotzbua** [comment]
Thanks. I will test.

**Comment by Rotzbua** [comment]
Some research and I found:
https://timdows.com/wp-content/uploads/2016/06/2016-07-06-20_44_14-768x678.png

So block0 is not just:
byte 0-3: uid
byte 4: check byte

It contains additionally:
byte 5: sak
byte 6: atqa0
byte 7: atqa1

Can you check if this sequence works?
> byte block0_buffer[] = {0x01, 0x02, 0x03, 0x04, 0x04, 0x08, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

**Comment by EndangeredF1sh** [comment]
OK, I will test tomorrow.

**Comment by EndangeredF1sh** [comment]
> Some research and I found:
> https://timdows.com/wp-content/uploads/2016/06/2016-07-06-20_44_14-768x678.png
> 
> So block0 is not just:
> byte 0-3: uid
> byte 4: check byte
> 
> It contains additionally:
> byte 5: sak
> byte 6: atqa0
> byte 7: atqa1
> 
> Can you check if this sequence works?
> 
> > byte block0_buffer[] = {0x01, 0x02, 0x03, 0x04, 0x04, 0x08, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

This sequence works well.
It seems that the manufacturer data (byte 8-15) has no influence to read.

**Comment by Rotzbua** [comment]
Thanks for pr and testing :+1:

**Pull request merged**
