### PR TITLE
Add servo.ino file

### PR DESCRIPTION
**Pull request by techied**
This file will control a servo instead of a relay.

### CODE REVIEW

**Comment by miguelbalboa** [comment]
Hello @techied 
Thank you for the example,
Can you please add the example in their own directory like ``examples/servoMotor/servo.ino``
And add the following line to ``.travis.yml`` in order to enable continuous integration int travis-ci for your example
```
    - PLATFORMIO_CI_SRC=examples/servoMotor/servo.ino
```
It would be very appreciated.
Cheers.

**Comment by techied** [comment]
Sure, doing it right now...

**Comment by techied** [comment]
Alright, I've added the line to the Travis CI and I made it's own folder!
Thank you!

**Comment by techied** [comment]
Oops, didn't even think when I added the line to the Travis CI.
Changing it now...

**Comment by techied** [comment]
There we go, it's checking
Should work now :) :smiley:

**Comment by techied** [comment]
Yup, it just passed!
Thank you!
(This was my first time using a 'Travis CI.' Sorry for any issues.)

**Comment by Rotzbua** [comment]
Hi, I think folder and *.ino-file must be named equal for IDE.

**Pull request merged**
