### PR TITLE
support for ESP8266 

### PR DESCRIPTION
**Pull request by beyondszine**
Hi,
I am trying to add support for ESP8266.  I have creaetd EEPROM library wrapper but as of now yet not updated the wiring in comments as I am facing some strange problems in git merge with your branch.
@omersiar Please help me out on this.  I am new to Git thing.  I tried Pulling from upstream (i.e. your branch) but it is having some merge error and screwing up all.  
Kindly look into it and let me know how to proceed for this.

### CODE REVIEW

**Comment by omersiar** [comment]
I always wanted to port it to ESP8266, it seems you have a quick solution for that. EEPROM functions bothered me, Arduino IDE Core for ESP was not matured enough at the time.

Since this Library was intended for the Atmel Chips and now it's cross-platform, I think we should not separate examples for the devices.

We should check whether if user wants to deploy the example on an UNO or ESP. I think IDE is smart enough for that, but I do not know how to implement it, yet. I will check #ifdef is applicable for this approach. 

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5-3rd-party-Hardware-specification
http://arduino.stackexchange.com/questions/4169/arduino-ide-ifdef

For now, you can create a development branch on your fork, make changes, test it and pull a request for merge. Since you are contributing to this Library which is appreciated, please do edit  changes.txt, so this will reduce stress on @Rotzbua who has write access.

Thank you for your work on that. Kind regards.

**Comment by beyondszine** [comment]
@omersiar
I have been working on ESP libraries for quite a time and as per my understanding It seems like that you are right when assuming the IDE is smart enough to know about the board for which it needs to include libraries. 
But I am not sure on the part where you where you provided the links for the same.  The support for the board have been added already. I am using arduino ide 1.8.1 with which I am **successfully** able to compile the accesscontrol code for nodemcu v1 board.
I will be testing my ported code on nodemcu v1 today only and will update you on its results.
And as you said, I will do the following:
1. creating the dev branch and then the pull request.
2. change the changes.txt

Doubt:
what to do with this pull request which i have already created, is there an option to take it back or something as I will make a new one from a new branch?

**Comment by omersiar** [comment]
I see now, you already handled ifdef. 

SPI_FLASH_SEC_SIZE  is this size is predictable? Is it a fixed size? or remaining flash size depending on program size?

Everything is ok, thank you again.

You can close a Pull Request.

**Comment by omersiar** [comment]
We also need to improve information at header.

**Pull request closed without merging**
