### PR TITLE
alterate Wipe button polling method without using other library

### PR DESCRIPTION
**Pull request by beyondszine**
Hi Miguelbalboa,
Plz let me know if lthis method suits more.
I am also thinking to implement exactly this using basic Timer interrupt or Tinker like adavnced lib,but they both need an additional include.
let me know if this works or needs any changes

### CODE REVIEW

**Comment by Rotzbua** [comment]
What is your opinion @omersiar ?

**Comment by omersiar** [comment]
I will test it this week, reviewing.

**Comment by omersiar** [comment]
uintN_t is broken somehow on 1.8.1 and 18.2 IDE. Sketch compiles but hardware stuck on line 145. IDK the other examples affected. I will investigate the reason further. Using int8_t instead solves the problem. I will inform the IDE team.

https://github.com/arduino/Arduino/issues/6148

@beyondszine Your approach is great, maybe we should get rid of all the delay() functions. Arduino examples should be simple for newcomers. This is why i used delays mostly.

**Comment by Rotzbua** [comment]
@omersiar thanks for your review.
I have one additional notice:
for `unsigned long` better use `uint32_t`
e.g.:
`unsigned long now = millis();` better use `uint32_t now = (uint32_t)millis();` 
typecast because on other boards millis() can be different. Arduino documentation is not consistent.

@beyondszine can you add this changes, so I can merge this?

**Comment by beyondszine** [comment]
@Rotzbua sure thing.

**Comment by beyondszine** [comment]
@omersiar I got into some work.  Will do it today itself.

**Pull request merged**
