### PR TITLE
Minor Example Update

### PR DESCRIPTION
**Pull request by omersiar**
Removed Problematic Servo Example
Added AccesControl example
Made changes to changes.txt

### CODE REVIEW

**Comment by Rotzbua** [comment]
@omersiar please fix the path to the example in travis.yaml otherwise the check will fail, thanks

**Comment by Rotzbua** [comment]
It would be nice if you change in the example all `int` to fixed sized integers, see https://en.wikibooks.org/wiki/C_Programming/C_Reference/stdint.h , thanks

**Comment by omersiar** [comment]
Since this is only example update, I guess it's ready to merge.

**Comment by Rotzbua** [comment]
seems good, thanks for your work!

**Pull request merged**
