### PR TITLE
Add Fritzing file for another version of the RC522 reader

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by Rotzbua** [comment]
@jose1711 whats the difference to the "normal"? Did you create this or somebody else?

**Comment by jose1711** [comment]
the board is a bit longer and has a slightly different layout. i did it myself based on version2 and the physical dimensions of a reader i purchased on *xpress.com.

**Comment by Rotzbua** [comment]
In 2-3 weeks I will have a closer look on it. Thanks so far for support :)

**Comment by Rotzbua** [comment]
@jose1711 Hi, I tried to open the part. I get an error while opening with a fresh fritz 0.9.3b. I suggest a mistake in the name or uid (maybe not a new unique?).

**Comment by jose1711** [comment]
i can confirm. in the meantime i also created a more precise version so let me put it together and try to fix the cannot-open problem as well. thank you for checking!

**Comment by jose1711** [comment]
i have amended the commit. can you see the difference now? thanks

**Comment by jose1711** [comment]
if you're okay with it then sure. i do not plan any futher changes to it. thank you and have a nice day!

**Pull request merged**
