### PR TITLE
Support esp32

### PR DESCRIPTION
**Pull request by andig**
Here is the missing PR for #443. Partially replaces #462.

### CODE REVIEW

**Comment by Rotzbua** [comment]
No explicit esp32 support

**Comment by andig** [comment]
According to #443 it does work. Why go to pains to NOT allow pulling the library on esp32 and instead force people to fork?

**Comment by Rotzbua** [comment]
Ok, sorry I misinterpreted your pr.

**Comment by andig** [comment]
Great, thank you!

**Pull request merged**
