### PR TITLE
New constructor and PCD_Init() method to allow defining arrays of rea…

### PR DESCRIPTION
**Pull request by lmmeng**
…ders.
Hello,

I'm using the library with these changes and I can define arrays of readers and use them in loops.
Attached is also a small example (ReadUidMultiReader.ino) to read the UID from 2 readers.

Regards,
Liviu

LE The "real" changes are few, the most of them are text formatting.

### CODE REVIEW

**Comment by miguelbalboa** [comment]
Thank you @lmmeng , The idea about have multiple readers out of the box is awesome,

But I'm afraid about if this changes break the another examples, for example https://github.com/miguelbalboa/rfid/blob/master/examples/ReadAndWrite/ReadAndWrite.ino

Are you sure that not anything else will be broken?, Maybe @Sthing @anistor or other can help

**Comment by Rotzbua** [comment]
I looked at the commit. It's a really bad idea to just copy the init-function and change only two lines. Because then you have to maintain two functions.
In my opinion it should look more like:
```arduino
void MFRC522::PCD_Init(byte chipSelectPin, byte resetPowerDownPin) {
  _chipSelectPin = chipSelectPin;
  _resetPowerDownPin = resetPowerDownPin;
  PCD_Init();
}
```

I didn't programmed for a while... but isn't it possible to use pointers? I modified your example.
```arduino
[...]
MFRC522 *mfrc522;

/**
 * Initialize.
 */
void setup() {
  Serial.begin(115200); // Initialize serial communications with the PC
  while (!Serial);    // Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)

  SPI.begin();        // Init SPI bus
  
  for (uint8_t reader = 0; reader < NR_OF_READERS; reader++) {
    mfrc522[reader] = MFRC522(ssPins[reader], RST_PIN); // Init MFRC522 object
    mfrc522[reader].PCD_Init(); // Init each MFRC522 card
  }
}
[...]
```

**Comment by lmmeng** [comment]
Hello all,
@Rotzbua : thanks for taking your time to look into this. Thank you also for the programming lesson, it helps the "hobby programmer" I am to write better code. :)
Unfortunately the pointer version you proposed doesn't work. It compiles, but when I'm trying to read a tag nothing happens.
A version with minimal changes in the MFRC522 library will be one with only the constructor overloaded and my sketch initialized as in your proposal, but with array instead of pointer (with pointer nothing happens here neither):
```code
[...]
MFRC522 mfrc522[NR_OF_PORTS];

/**
 * Initialize.
 */
void setup() {
  Serial.begin(115200); // Initialize serial communications with the PC
  while (!Serial);    // Do nothing if no serial port is opened (added for Arduinos based on ATMEGA32U4)

  SPI.begin();        // Init SPI bus

  for (uint8_t reader = 0; reader < NR_OF_READERS; reader++) {
    mfrc522[reader] = MFRC522(ssPins[reader], RST_PIN); // Init MFRC522 object
    mfrc522[reader].PCD_Init(); // Init each MFRC522 card
  }
}
[...]
```
It compiles and works. As I said, I'm just a hobby programmer, but I think this version doubles the number of MFRC522 objects I'll finally have (the size of the compiled code is, for sure, some bytes bigger than the "full changed" version). 
For that reason, I find the version with the constructor and the PCD_Init() method overloaded (with the changes in the PCD_Init() you pointed out, of course) the best one. 
I've updated my fork with the updated version of the PCD_Init() method (and the original, not reformatted sources).

@miguelbalboa : thank you for considering my proposed changes. 
In my opinion, my changes shouldn’t break the old examples. The original constructor/method and my overloads are different enough (the number and type of arguments) to allow the compiler to choose the right one in each case. I've compiled the ReadAndWrite.ino example with the changed library and is still working. 
But if you have any doubt, please ignore my pull request. :)

Best regards,
Liviu

**Comment by miguelbalboa** [comment]
Thank you @lmmeng , because I don't have a reader right now, that is why i'm asking if the others ways to use the library are affected in order to not affect other users. To be honest has been a long time since I wrote code for Arduino, and is nice to ear that you can compile the others examples, It's what I need to know.
Thanks @Rotzbua for your review, has been very helpful.

**Comment by lmmeng** [comment]
I also thank you, @miguelbalboa and @Rotzbua for your support and understanding. 
I will now delete my fork and leave only the reference to the original.

**Pull request merged**
