### PR TITLE
Use settings functions on SPI libraries.

### PR DESCRIPTION
**Pull request by sophiekovalevsky**
There are new methods to work properly with the SPI library an prevent bus conflicts.
I've added a code to work with them, this delete the method setSPIConfig used on PCD_Init(). With these, now it's possible to work with several devices (if anyone needs that features) using the specific settings for them without intefering each other. I've tested some examples code and it's working properly.

### CODE REVIEW

**Comment by miguelbalboa** [comment]
Thank you @sophiekovalevsky 

I'm not sure if this change will affect the behavior and break something.
What is the different between your approach and this example: [ReadUidMultiReader.ino](/miguelbalboa/rfid/blob/master/examples/ReadUidMultiReader/ReadUidMultiReader.ino)

Maybe @lmmeng can help.
Greetings.

**Comment by sophiekovalevsky** [comment]
Thanks for the response.
SPI libraries made some modifications to work properly with different devices that use the same BUS but with differents parameters. In the case of ReadUidMultiReader.ino we are using differents devices with the same parameters. But in future projects, somebody maybe want to use the module together with another device that use SPI either, e.g. an LCD. Even if some SPI device is used with interrupts, that could lead in wrong results due the fact that another SPI device is communicating at the same time. Please, see more reference here [0], [1].

[0] https://www.pjrc.com/teensy/td_libs_SPI.html
[1] http://dorkbotpdx.org/blog/paul/spi_transactions_in_arduino

I've made some test with examples code within library and is working. But you're right, maybe in some others code, may be corrupt the info. 

I think we should do some test with the rest of the examples code currently available in the library.

**Comment by lmmeng** [comment]
Hello all,
in my opinion the changes proposed by @sophiekovalevsky are OK and doesn't brake anything; to be sure I'll test my sketches and let you know the result. Unfortunately it will take a little time until I'll be able to do it.

Regards,
Liviu

**Comment by lmmeng** [comment]
Hello all,
my sketches are still working with the @sophiekovalevsky's changes.
@sophiekovalevsky: you have an (copy-paste?) error in the MFRC522.cpp file (line 1772). You have 
```
PICC_ReadCardSerial()MFRC522::StatusCode MFRC522::PCD_NTAG216_AUTH(byte *passWord, byte pACK[]) //Authenticate with 32bit password
```
and should be
```
MFRC522::StatusCode MFRC522::PCD_NTAG216_AUTH(byte *passWord, byte pACK[]) //Authenticate with 32bit password
```

**Comment by sophiekovalevsky** [comment]
Hi there @lmmeng.
Thanks for testing your code. 
I was wondering where the copy paste error is since the commit changes are only referred to spi code within library. I don't see any error as you have commented, could you please take at look again?

Best regards!

**Comment by lmmeng** [comment]
Hello @sophiekovalevsky,
I mean the MFRC522.cpp file (https://github.com/sophiekovalevsky/rfid/blob/master/MFRC522.cpp), line 1772. I can still seeing 
```
PICC_ReadCardSerial()MFRC522::StatusCode MFRC522::PCD_NTAG216_AUTH(byte *passWord, byte pACK[]) //Authenticate with 32bit password
{
```

**Comment by sophiekovalevsky** [comment]
I've recently update my master branch from @miguelbalboa repo. I suposse that this is an typo error in recents commints. Thanks to notice.

Have you test the code with the spi branch instead master?

**Comment by sophiekovalevsky** [comment]
I've updated my master repo, error type was fixed in recent commits from @miguelbalboa repo.

**Comment by lmmeng** [comment]
Hello @sophiekovalevsky,
you have right, I've used the wrong repo (master). 
I've redone the tests with the spi branch and my sketches are still working.

**Comment by sophiekovalevsky** [comment]
Thanks for retesting the codes.
@miguelbalboa what do you think?

**Pull request merged**
