### PR TITLE
Arduino and RFID

### PR DESCRIPTION
**Pull request by biribiri71**
hi, I need your help with Arduino and RFID MRC522. I need a program that reads the card blocks and stores them in an array, reads the UID of the card and saves it in a variable, then instead, the opposite direction, that is, write the card blocks with values ​​in an array and write to the UID of the card with a code contained in a variable .. I hope for your help because I'm desperate with a school project to be urgent, sorry, unfortunately I do not speak English and I had to rely on google translator
>
> Thanks you

### CODE REVIEW

**Comment by biribiri71** [comment]
I do not think I have found an answer to my question, but not if it was my fault or why no one managed to help me, however, miguelbalboa could add an example with a program to Arduino to do what I need?
In case I have not found the answer you would be kind enough to make me find?

**Comment by biribiri71** [comment]
I'd like to speak with you, Miguelbalboa, This is my Email Address biral.cristiano@me.com

**Comment by Rotzbua** [comment]
You will not get support for your individual software/programming problems. Visit http://forum.arduino.cc/  or so..

@miguelbalboa This Pull Request can be cancelled/closed.

**Comment by biribiri71** [comment]
I asked for an example with a program that does this , unfortunately the library is not easily understood and it would seem that no one has the skills to deal with this library , so I'm asking for your help !

**Comment by Rotzbua** [comment]
1. Generally are libraries for embedded systems are not easy.
1. Your problem has nothing to do with a **pull request**. At least it is more a issue.
1. I told you, that for programming questions you have to visit a forum etc. which is specialized for programming. Here you only get help if you find an error in the library.
1. There are many examples. Some print byte by byte to Serial. So it should be easy to write it to an array instead of Serial.

Best

**Comment by miguelbalboa** [comment]
Bad pull request.

**Pull request closed without merging**
